version: 2
# CircleCI integration with Drupal 8.

## Defines images and working directory.
defaults: &defaults
  docker:
    - image: pookmish/drupal8ci:latest
    - image: selenium/standalone-chrome:3.141.59-neon
    - image: mariadb:10.3
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
  working_directory: /var/www/html


#Jobs
prep_tests: &prep_tests
  <<: *defaults
  steps:
    - checkout:
        path: /var/www/test
    - run: /var/www/test/.circleci/build.sh

# Declare all of the jobs we should run.
jobs:
  run-prep:
    <<: *prep_tests

# Declare a workflow that runs all of our jobs in parallel.
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - run-prep
