version: 2
# CircleCI integration with Drupal 8.

## Defines images and working directory.
defaults: &defaults
  docker:
    - image: pookmish/drupal8ci:latest
    - image: selenium/standalone-chrome:3.141.59-neon
    - image: mariadb:10.3
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
  working_directory: /var/www/html

#Jobs
prep_tests: &prep_tests
  <<: *defaults
  steps:
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    - run:
        name: Directory Setup
        command: cd /var/www && rm -rf html && composer create-project drupal-composer/drupal-project:8.x-dev html --no-interaction
    - run:
        command: |
          ln -s web docroot
          echo "composer config repositories.module vcs $CIRCLE_REPOSITORY_URL"
          composer config repositories.module vcs $CIRCLE_REPOSITORY_URL
          composer require $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:dev-$CIRCLE_BRANCH
    - checkout:
        path: /var/www/html/docroot/modules/custom
    - run:
        name: Install
        command: |
          cp /var/www/html/docroot/modules/custom/$CIRCLE_PR_REPONAME/.circleci/phpunit.xml /var/www/html/docroot/core/
          cd docroot && ../vendor/bin/phpunit -c core modules/custom
    - save_cache:
        paths:
          - .
        key: v1-dependencies-{{ checksum "composer.lock" }}

# Declare all of the jobs we should run.
jobs:
  run-prep:
    <<: *prep_tests

# Declare a workflow that runs all of our jobs in parallel.
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - run-prep
